# Generated by Django 4.2.10 on 2024-02-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_book_id_circulation_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.book"
            ),
        ),
    ]
