# Generated by Django 4.2.10 on 2024-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_reservation_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circulation",
            name="event_type",
        ),
        migrations.AddField(
            model_name="circulation",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
